### PR TITLE
change docroot: WP docker image installs into /usr/src/

### PR DESCRIPTION
**Pull request by drzraf**
https://github.com/docker-library/wordpress/blob/master/php5.6/fpm-alpine/Dockerfile#L52

### CODE REVIEW

**Comment by iamdb** [comment]
Can you elaborate on why this needs to match?

**Comment by drzraf** [comment]
Actually it's more about `SCRIPT_FILENAME` than `DOCUMENT_ROOT`
Point is that nginx send a fgci request which define the absolute path that php-fpm must look for.
But php-fpm comes from `iamdb/fpm-bedrock-wordpress` which inherit from `php:7.0-fpm-alpine`
It would be logical to rely upon wordpress-alpine-php-fpm image (that's how I personally overrode docker-compose) which ... uses `/usr/src/wordpress` (although it's not very LHS-friendly)

**Comment by iamdb** [comment]
I can see what you're saying now, but I'm going to reject this pull request. The Wordpress fpm doesn't install Wordpress to `/usr/src/wordpress`. If you dig deeper, in the `docker-entrypoint.sh` file you'll notice that it looks for a copy of Wordpress in the folder and then copies the install to `/var/www/html`. If you wish to use the Wordpress image, you can do so by just editing the `docker-compose.yml` file. If you wish to use the Wordpress image as a base, you can do that as well and just replace my fpm image with your own. I may update this in the future to support Wordpress' fpm images, but I don't see the benefit at the moment and this merge doesn't fix anything.

Regards,
David

**Comment by drzraf** [comment]
adding `/var/www/html/web` as a volume to the fpm image bind mount `/usr/src/wordpress` to the expected location without a need to change the nginx Docker image.
in  my case that was an acceptable workaround
(I still don't understand why the fcgi protocol expects webserver path (SCRIPT_FILENAME + DOCUMENT_ROOT to be the same for the cgid (php-fpm) daemon path)

**Pull request closed without merging**
